<?php
$elementos = array(
    ["id" => "1", "simbolo" => "H", "clase" => "otrosNoMetales"],
    ["id" => "2", "simbolo" => "He", "clase" => "gasesNobles"],

    ["id" => "3", "simbolo" => "Li", "clase" => "alcalinos"],
    ["id" => "4", "simbolo" => "Be", "clase" => "alcalinoterreos"],
    ["id" => "5", "simbolo" => "B", "clase" => "metaloides"],
    ["id" => "6", "simbolo" => "C", "clase" => "otrosNoMetales"],
    ["id" => "7", "simbolo" => "N", "clase" => "otrosNoMetales"],
    ["id" => "8", "simbolo" => "O", "clase" => "otrosNoMetales"],
    ["id" => "9", "simbolo" => "F", "clase" => "halogenos"],
    ["id" => "10", "simbolo" => "Ne", "clase" => "gasesNobles"],

    ["id" => "11", "simbolo" => "Na", "clase" => "alcalinos"],
    ["id" => "12", "simbolo" => "Mg", "clase" => "alcalinoterreos"],
    ["id" => "13", "simbolo" => "Al", "clase" => "otrosMetales"],
    ["id" => "14", "simbolo" => "Si", "clase" => "metaloides"],
    ["id" => "15", "simbolo" => "P", "clase" => "otrosNoMetales"],
    ["id" => "16", "simbolo" => "S", "clase" => "otrosNoMetales"],
    ["id" => "17", "simbolo" => "Cl", "clase" => "halogenos"],
    ["id" => "18", "simbolo" => "Ar", "clase" => "gasesNobles"],

    ["id" => "19", "simbolo" => "K", "clase" => "alcalinos"],
    ["id" => "20", "simbolo" => "Ca", "clase" => "alcalinoterreos"],
    ["id" => "21", "simbolo" => "Sc", "clase" => "bloqueD"],
    ["id" => "22", "simbolo" => "Ti", "clase" => "bloqueD"],
    ["id" => "23", "simbolo" => "V", "clase" => "bloqueD"],
    ["id" => "24", "simbolo" => "Cr", "clase" => "bloqueD"],
    ["id" => "25", "simbolo" => "Mn", "clase" => "bloqueD"],
    ["id" => "26", "simbolo" => "Fe", "clase" => "bloqueD"],
    ["id" => "27", "simbolo" => "Co", "clase" => "bloqueD"],
    ["id" => "28", "simbolo" => "Ni", "clase" => "bloqueD"],
    ["id" => "29", "simbolo" => "Cu", "clase" => "bloqueD"],
    ["id" => "30", "simbolo" => "Zn", "clase" => "bloqueD"],
    ["id" => "31", "simbolo" => "Ga", "clase" => "otrosMetales"],
    ["id" => "32", "simbolo" => "Ge", "clase" => "metaloides"],
    ["id" => "33", "simbolo" => "As", "clase" => "metaloides"],
    ["id" => "34", "simbolo" => "Se", "clase" => "otrosNoMetales"],
    ["id" => "35", "simbolo" => "Br", "clase" => "halogenos"],
    ["id" => "36", "simbolo" => "Kr", "clase" => "gasesNobles"],

    ["id" => "37", "simbolo" => "Rb", "clase" => "alcalinos"],
    ["id" => "38", "simbolo" => "Sr", "clase" => "alcalinoterreos"],
    ["id" => "39", "simbolo" => "Y", "clase" => "bloqueD"],
    ["id" => "40", "simbolo" => "Zr", "clase" => "bloqueD"],
    ["id" => "41", "simbolo" => "Nb", "clase" => "bloqueD"],
    ["id" => "42", "simbolo" => "Mo", "clase" => "bloqueD"],
    ["id" => "43", "simbolo" => "Tc", "clase" => "bloqueD"],
    ["id" => "44", "simbolo" => "Ru", "clase" => "bloqueD"],
    ["id" => "45", "simbolo" => "Rh", "clase" => "bloqueD"],
    ["id" => "46", "simbolo" => "Pd", "clase" => "bloqueD"],
    ["id" => "47", "simbolo" => "Ag", "clase" => "bloqueD"],
    ["id" => "48", "simbolo" => "Cd", "clase" => "bloqueD"],
    ["id" => "49", "simbolo" => "In", "clase" => "otrosMetales"],
    ["id" => "50", "simbolo" => "Sn", "clase" => "otrosMetales"],
    ["id" => "51", "simbolo" => "Sb", "clase" => "metaloides"],
    ["id" => "52", "simbolo" => "Te", "clase" => "metaloides"],
    ["id" => "53", "simbolo" => "I", "clase" => "halogenos"],
    ["id" => "54", "simbolo" => "Xe", "clase" => "gasesNobles"],

    ["id" => "55", "simbolo" => "Cs", "clase" => "alcalinos"],
    ["id" => "56", "simbolo" => "Ba", "clase" => "alcalinoterreos"],
    ["id" => "57-71", "simbolo" => "La-Lu", "clase" => "lantanidos"],
    ["id" => "72", "simbolo" => "Hf", "clase" => "bloqueD"],
    ["id" => "73", "simbolo" => "Ta", "clase" => "bloqueD"],
    ["id" => "74", "simbolo" => "W", "clase" => "bloqueD"],
    ["id" => "75", "simbolo" => "Re", "clase" => "bloqueD"],
    ["id" => "76", "simbolo" => "Os", "clase" => "bloqueD"],
    ["id" => "77", "simbolo" => "Ir", "clase" => "bloqueD"],
    ["id" => "78", "simbolo" => "Pt", "clase" => "bloqueD"],
    ["id" => "79", "simbolo" => "Au", "clase" => "bloqueD"],
    ["id" => "80", "simbolo" => "Hg", "clase" => "bloqueD"],
    ["id" => "81", "simbolo" => "Tl", "clase" => "otrosMetales"],
    ["id" => "82", "simbolo" => "Pb", "clase" => "otrosMetales"],
    ["id" => "83", "simbolo" => "Bi", "clase" => "otrosMetales"],
    ["id" => "84", "simbolo" => "Po", "clase" => "metaloides"],
    ["id" => "85", "simbolo" => "At", "clase" => "halogenos"],
    ["id" => "86", "simbolo" => "Rn", "clase" => "gasesNobles"],

    ["id" => "87", "simbolo" => "Fr", "clase" => "alcalinos"],
    ["id" => "88", "simbolo" => "Ra", "clase" => "alcalinoterreos"],
    ["id" => "89-103", "simbolo" => "Ac-Lr", "clase" => "actinidos"],
    ["id" => "104", "simbolo" => "Rf", "clase" => "bloqueD"],
    ["id" => "105", "simbolo" => "Db", "clase" => "bloqueD"],
    ["id" => "106", "simbolo" => "Sg", "clase" => "bloqueD"],
    ["id" => "107", "simbolo" => "Bh", "clase" => "bloqueD"],
    ["id" => "108", "simbolo" => "Hs", "clase" => "bloqueD"],
    ["id" => "109", "simbolo" => "Mt", "clase" => "bloqueD"],
    ["id" => "110", "simbolo" => "Ds", "clase" => "bloqueD"],
    ["id" => "111", "simbolo" => "Rg", "clase" => "bloqueD"],
    ["id" => "112", "simbolo" => "Cn", "clase" => "bloqueD"],
    ["id" => "113", "simbolo" => "Nh", "clase" => "otrosMetales"],
    ["id" => "114", "simbolo" => "Fl", "clase" => "otrosMetales"],
    ["id" => "115", "simbolo" => "Mc", "clase" => "otrosMetales"],
    ["id" => "116", "simbolo" => "Lv", "clase" => "otrosMetales"],
    ["id" => "117", "simbolo" => "Ts", "clase" => "halogenos"],
    ["id" => "118", "simbolo" => "Og", "clase" => "gasesNobles"],

    ["id" => "57", "simbolo" => "La", "clase" => "lantanidos"],
    ["id" => "58", "simbolo" => "Ce", "clase" => "lantanidos"],
    ["id" => "59", "simbolo" => "Pr", "clase" => "lantanidos"],
    ["id" => "60", "simbolo" => "Nd", "clase" => "lantanidos"],
    ["id" => "61", "simbolo" => "Pm", "clase" => "lantanidos"],
    ["id" => "62", "simbolo" => "Sm", "clase" => "lantanidos"],
    ["id" => "63", "simbolo" => "Eu", "clase" => "lantanidos"],
    ["id" => "64", "simbolo" => "Gd", "clase" => "lantanidos"],
    ["id" => "65", "simbolo" => "Tb", "clase" => "lantanidos"],
    ["id" => "66", "simbolo" => "Dy", "clase" => "lantanidos"],
    ["id" => "67", "simbolo" => "Ho", "clase" => "lantanidos"],
    ["id" => "68", "simbolo" => "Er", "clase" => "lantanidos"],
    ["id" => "69", "simbolo" => "Tm", "clase" => "lantanidos"],
    ["id" => "70", "simbolo" => "Yb", "clase" => "lantanidos"],
    ["id" => "71", "simbolo" => "Lu", "clase" => "lantanidos"],

    ["id" => "89", "simbolo" => "Ac", "clase" => "actinidos"],
    ["id" => "90", "simbolo" => "Th", "clase" => "actinidos"],
    ["id" => "91", "simbolo" => "Pa", "clase" => "actinidos"],
    ["id" => "92", "simbolo" => "U", "clase" => "actinidos"],
    ["id" => "93", "simbolo" => "Np", "clase" => "actinidos"],
    ["id" => "94", "simbolo" => "Pu", "clase" => "actinidos"],
    ["id" => "95", "simbolo" => "Am", "clase" => "actinidos"],
    ["id" => "96", "simbolo" => "Cm", "clase" => "actinidos"],
    ["id" => "97", "simbolo" => "Bk", "clase" => "actinidos"],
    ["id" => "98", "simbolo" => "Cf", "clase" => "actinidos"],
    ["id" => "99", "simbolo" => "Es", "clase" => "actinidos"],
    ["id" => "100", "simbolo" => "Fm", "clase" => "actinidos"],
    ["id" => "101", "simbolo" => "Md", "clase" => "actinidos"],
    ["id" => "102", "simbolo" => "No", "clase" => "actinidos"],
    ["id" => "103", "simbolo" => "Lr", "clase" => "actinidos"],

);

?>